# ?????
weights: ./work_dir/st_gcn/epoch0_model.pt

# feeder
feeder: feeder.feeder_fds.Feeder_fds
test_feeder_args:
  data_path: ./data/FineDiving/test_data.npy
  label_path: ./data/FineDiving/test_label.pkl
  diff_path: ./data/FineDiving/test_diff.pkl
  judge_path: ./data/FineDiving/test_judge.npy
  judge: single


# model
model: net.st_gcn.Model
judge_type: single
loss_type: mix1
model_args:
  in_channels: 3
  # ???????
  num_class: 101
  dropout: 0.5
  edge_importance_weighting: True
  num_judge: 1
  model_type: single
  graph_args:
    layout: 'GHUM'
    strategy: 'spatial'

# test 
phase: test
device: [0]
test_batch_size: 64

