# ?????
# weights: ./work_dir/st_gcn/epoch0_model_reg.pt

# feeder
feeder: feeder.feeder_fds.Feeder_fds
test_feeder_args:
  data_path: ./data/FineDiving/test_data.npy
  label_path: ./data/FineDiving/test_label.pkl
  diff_path: ./data/FineDiving/test_diff.pkl
  judge_path: ./data/FineDiving/test_judge.npy
  judge: mult


# model
model: net.st_gcn.Model
judge_type: mult
loss_type: mse
model_args:
  in_channels: 3
  # ???????
  num_class: 21
  dropout: 0.5
  edge_importance_weighting: True
  num_judge: 3
  model_type: mult
  graph_args:
    layout: 'GHUM'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

