work_dir: ./work_dir/recognition/fds/ST_GCN

# feeder
feeder: feeder.feeder_fds.Feeder_fds
train_feeder_args:
  data_path: ./data/FineDiving/train_data.npy
  label_path: ./data/FineDiving/train_label.pkl
test_feeder_args:
  data_path: ./data/FineDiving/val_data.npy
  label_path: ./data/FineDiving/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  # ????????
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'GHUM'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.0005
step: [10, 50]

# training
device: [0]
batch_size: 64 
test_batch_size: 64
num_epoch: 100



