work_dir: ./work_dir/recognition/fds/ST_GCN_mult

# feeder
feeder: feeder.feeder_fds.Feeder_fds
train_feeder_args:
  data_path: ./data/FineDiving/train_data.npy
  label_path: ./data/FineDiving/train_label.pkl
  diff_path: ./data/FineDiving/train_diff.pkl
  judge_path: ./data/FineDiving/train_judge.npy
  judge: mult

test_feeder_args:
  data_path: ./data/FineDiving/test_data.npy
  label_path: ./data/FineDiving/test_label.pkl
  diff_path: ./data/FineDiving/test_diff.pkl
  judge_path: ./data/FineDiving/test_judge.npy
  judge: mult



# model
model: net.st_gcn.Model
judge_type: mult
loss_type: mix1
model_args:
  in_channels: 3
  # ????????
  num_class: 21
  dropout: 0.5
  edge_importance_weighting: True
  num_judge: 3
  model_type: mult
  graph_args:
    layout: 'GHUM'
    strategy: 'spatial'

#optim
optimizer: SGD
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 64 
test_batch_size: 64
num_epoch: 100

weights: ./work_dir/st_gcn_mult/epoch0_model.pt

