work_dir: ./work_dir/recognition/fds/ST_GCN_RGB

# feeder
feeder: feeder.feeder_fds_with_clip.Feeder_fds_with_clip
train_feeder_args:
  data_path: ./data/FineDiving/train_data.npy
  label_path: ./data/FineDiving/train_label.pkl
  diff_path: ./data/FineDiving/train_diff.pkl
  rgb_path: ./data/FineDiving/train_rgb.npy
  judge_path: ./data/FineDiving/train_judge.npy
  judge: single

test_feeder_args:
  data_path: ./data/FineDiving/test_data.npy
  label_path: ./data/FineDiving/test_label.pkl
  diff_path: ./data/FineDiving/test_diff.pkl
  rgb_path: ./data/FineDiving/test_rgb.npy
  judge_path: ./data/FineDiving/test_judge.npy
  judge: single



# model
model: net.st_gcn_with_rgb_i3d.Model
judge_type: single
loss_type: mix1
model_args:
  in_channels: 3
  # ????????
  num_class: 101
  dropout: 0.5
  edge_importance_weighting: True
  num_judge: 1
  model_type: single
  graph_args:
    layout: 'GHUM'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.001
step: [10, 50]

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 30



weights: ./work_dir/st_gcn_with_rgb/epoch0_model.pt
